language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "iojs"
env:
  - NODE_ENV=travis
services:
  - mongodb
  - redis
before_install:
  - "npm install -g bower watchify browserify nodemon forever mocha"
