language: node_js
node_js:
  - "4.2.1"
  - "iojs"
env:
  - NODE_ENV=travis
services:
  - mongodb
before_install:
  - "npm install -g bower watchify browserify nodemon forever mocha"
  - "wget https://github.com/nats-io/gnatsd/releases/download/v0.6.8/gnatsd-v0.6.8-linux-amd64.tar.gz ~/gnatsd.tar.gz"
  - "tar -xvzf ~/gnatsd.tar.gz -C ~/gnatsd"
  - "nohup exec ~/gnatsd/gnatsd"
